### ISSUE TITLE
Invoke-PnPSiteTemplate: You already have a full width section on this page, you can't add a section with vertical column

### ISSUE THREAD

**Issue by till-llit** [pnp/pnpframework#1058]
might be related to #1043 

PnP.PowerShell 2.10.0

Reproducible on Tenants in Standard Release and Targeted Release.

Steps to Repro:

1. Communication Site -> New Page -> Blank Template
2. Add a "Vertical Section" and put a text webpart in both sections (left and vertical). Give the page a Title.
3. export-pnppage  "PageWithVerticalSection.aspx" -Out PageWithVerticalSection.xml
4. invoke-pnpsitetemplate -path PageWithVerticalSection.xml

Error:

> Invoke-PnPSiteTemplate: You already have a full width section on this page, you can't add a section with vertical column

XML Export File:

><pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2022/09/ProvisioningSchema">
  <pnp:Preferences Generator="PnP.Framework, Version=1.17.15.0, Culture=neutral, PublicKeyToken=0d501f89f11b748c" />
  <pnp:Templates ID="CONTAINER-TEMPLATE-5E5536E0AF284E9594B8FDE1FAF1C06C">
    <pnp:ProvisioningTemplate ID="TEMPLATE-5E5536E0AF284E9594B8FDE1FAF1C06C" Version="0" Scope="Undefined">
      <pnp:ClientSidePages>
        <pnp:ClientSidePage PromoteAsNewsArticle="false" PromoteAsTemplate="false" Overwrite="true" Title="PageWithVerticalSection" ThumbnailUrl="" PageName="PageWithVerticalSection.aspx">
          <pnp:Header Type="Default" LayoutType="FullWidthImage" ShowTopicHeader="false" ShowPublishDate="false" ShowBackgroundGradient="false" TopicHeader="" AlternativeText="" Authors="" AuthorByLineId="15" />
          <pnp:Sections>
            <pnp:Section Order="1" Type="OneColumnFullWidth">
              <pnp:Controls>
                <pnp:CanvasControl WebPartType="PageTitle" JsonControlData="..." Order="1" Column="1" />
              </pnp:Controls>
            </pnp:Section>
            <pnp:Section Order="2" Type="OneColumnVerticalSection">
              <pnp:Controls>
                <pnp:CanvasControl WebPartType="Text" ControlId="1212fc8d-dd6b-408a-8d5d-9f1cc787efbb" Order="1" Column="1">
                  <pnp:CanvasControlProperties>
                    <pnp:CanvasControlProperty Key="Text" Value="left text" />
                  </pnp:CanvasControlProperties>
                </pnp:CanvasControl>
                <pnp:CanvasControl WebPartType="Text" ControlId="4be22244-57dc-4e78-a973-7293e75ef353" Order="1" Column="2">
                  <pnp:CanvasControlProperties>
                    <pnp:CanvasControlProperty Key="Text" Value="vertical text" />
                  </pnp:CanvasControlProperties>
                </pnp:CanvasControl>
              </pnp:Controls>
            </pnp:Section>
          </pnp:Sections>
        </pnp:ClientSidePage>
      </pnp:ClientSidePages>
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>

**Comment by tarjeieo** [comment]
Seeing the same issue.

**Comment by paalolav** [comment]
Same issue here with a customer on targeted release with the branding central Preview. Could it be that PnP Powershell has issues reading the new page header options in SharePoint?

**Comment by paalolav** [comment]
I've done some digging. It seems related to the new header in SharePoint pages.
Test this please:
1. Remove the following data from your template"
"<pnp:Section Order="1" Type="OneColumnFullWidth">
pnp:Controls
<pnp:CanvasControl WebPartType="PageTitle" JsonControlData="..." Order="1" Column="1" />
</pnp:Controls>
</pnp:Section>"
In the next line, change <pnp:Section Order="2" Type="OneColumnVerticalSection"> to <pnp:Section Order="1" Type="OneColumnVerticalSection">
Save the template file and Invoke it. Should work.

**Comment by till-llit** [comment]
@paalolav : yes, it is related to the new way to save the header as a "OneColumnFullWidth". when i remove it from the template everything works as expected.

i guess the import script must be updated to allow this combination of Controls

**Comment by paalolav** [comment]
@till-llit We've done further testing. This is a big issue for light provisioning automations at the moment. Hope that the PnP teams is on this and updates the import.

**Comment by czullu** [comment]
@paalolav @till-llit  Paalolav is right about the Order. The current Logic is, that the first section shalle be OneColumnFullWith ad the Control in it of Type PageTitle. The reason for the current check is, that the XML-Schema of PNP does not allow to specify the new Header Type and therefore we need to have it under HeaderType-Default and check after the fact.

Have the Pages you have issues with been created new or have they been converted during save from old layout to new? You can check this on Page-Field-History Field CanvasControl1.

The way i understand it, we should be good if i change the code in a way that i check if we have any section of type OneColumnFullWidth with the PageTitle.WebPart in it and then set modern header and reorder the rest of the sections.

**Comment by till-llit** [comment]
@czullu : i did my tests both, with brand new pages and existing pages. both scenarios fail when there are other sections than onecolumn after the new header section.

**Comment by czullu** [comment]
> @czullu : i did my tests both, with brand new pages and existing pages. both scenarios fail when there are other sections than onecolumn after the new header section.

I mad the fixes for pnpcore and pnpframework and they have been merged to dev branch. You will have to use beta version of pnp powershell until next official release.

**Comment by till-llit** [comment]
> Have the Pages you have issues with been created new or have they been converted during save from old layout to new? You can check this on Page-Field-History Field CanvasControl1.

i was referring to this question in the post before, have not yet tested the dev branch


> I mad the fixes for pnpcore and pnpframework and they have been merged to dev branch. You will have to use beta version of pnp powershell until next official release.

im currently trying to figure out how to include the nightly build in our azure function and let you know how it works once im done.

and thank you for your efforts!

**Comment by till-llit** [comment]
i still see the same error with 2.12.21    nightly    PnP.PowerShell

**Comment by czullu** [comment]
> i still see the same error with 2.12.21 nightly PnP.PowerShell

Did you reexport the template-xml? You need to as the detection was to strict and you have wrong header info in xml.

**Comment by till-llit** [comment]
yes i did - i just tried it again. attached is my exported xml, you should see the same error during import
[PageWithVerticalSection.xml.txt](https://github.com/user-attachments/files/17199707/PageWithVerticalSection.xml.txt)
 
(had to mask it as a txt file, github does not like xml)

**Comment by PedroMordeP** [comment]
> yes i did - i just tried it again. attached is my exported xml, you should see the same error during import [PageWithVerticalSection.xml.txt](https://github.com/user-attachments/files/17199707/PageWithVerticalSection.xml.txt)
> 
> (had to mask it as a txt file, github does not like xml)

Today I came across with the same problem when provisioning a template in which there is a page with a OneColumnFullWidth and a OneColumnVerticalSection.

I updated to PnP.Framework using @czullu fix mentioned and updated PnP.Core to 1.14.110-nightly and continue with the same issue. 
There still breaks in PnP.Core when adding the OneColumnVerticalSection.

```
PnP.Core.ClientError
PnP.Core.ClientException: You already have a full width section on this page, you can't add a section with vertical column
   at PnP.Core.Model.SharePoint.Page.CanThisSectionBeAdded(CanvasSection section)
   at PnP.Core.Model.SharePoint.Page.AddSection(ICanvasSection section)
   at PnP.Core.Model.SharePoint.Page.AddSection(CanvasSectionTemplate sectionTemplate, Single order, Int32 zoneEmphasis, Nullable`1 verticalSectionZoneEmphasis)
   at PnP.Framework.Provisioning.ObjectHandlers.ObjectClientSidePages.CreatePage(Web web, ProvisioningTemplate template, TokenParser parser, PnPMonitoredScope scope, BaseClientSidePage clientSidePage, String pagesLibrary, List pagesLibraryList, Int32& currentPageIndex, List`1 preCreatedPages) in C:\B\Repos\PnP.Framework\src\lib\PnP.Framework\Provisioning\ObjectHandlers\ObjectClientSidePages.cs:line 482
   at PnP.Framework.Provisioning.ObjectHandlers.ObjectClientSidePages.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation) in C:\B\Repos\PnP.Framework\src\lib\PnP.Framework\Provisioning\ObjectHandlers\ObjectClientSidePages.cs:line 162
   at PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo, Boolean calledFromHierarchy, TokenParser tokenParser) in C:\B\Repos\PnP.Framework\src\lib\PnP.Framework\Provisioning\ObjectHandlers\SiteToTemplateConversion.cs:line 457
```

**Comment by till-llit** [comment]
fixed with fixed with https://github.com/pnp/pnpcore/pull/1629
