### ISSUE TITLE
[BUG] KeepPageCreationModificationInformation switch causing error on publishingpage transformation using ConvertTo-PnPClientSidePage

### ISSUE THREAD

**Issue by phil-maynard** [pnp/pnpframework#108]
Thank you for reporting a bug. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Problem Area

[X ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Published news article hosted in classic site in SharePoint online converted to client side page in communication site on same tenant using the KeepPageCreationModificationInformation switch to maintain the original author, editor, created and modified information.

#### Observed Behavior

command failed with the error message:
```
_The property or field has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.   at Microsoft.SharePoint.Client.ListItem.GetFieldValue(String fieldName)
   at SharePointPnP.Modernization.Framework.Transform.BasePageTransformator.StoreSourcePageInformationToKeep(ListItem sourcePage)
   at SharePointPnP.Modernization.Framework.Publishing.PublishingPageTransformator.Transform(PublishingPageTransformationInformation publishingPageTransformationInformation)_ 
```
When the _KeepPageCreationModificationInformation_ switch is removed the page is converted successfully but the author and editor information is not migrated which is causing us a problem.

#### Steps to Reproduce

```
ConvertTo-PnPClientSidePage `
-Identity '************page.aspx' `
-PublishingPage `
-KeepPageCreationModificationInformation `
-PostAsNews `
-Overwrite `
-LogVerbose -LogType File -LogFolder c:\temp\Logs `
-TargetWebUrl https://***************.sharepoint.com/sites/news01 `
-PageLayoutMapping 'C:\Temp\custompagelayoutmapping.xml'
```

#### SharePointPnPPowerShellOnline version
3.26.2010.0

# Modernization Summary Report

Date  |  Duration  |  Source Page  |  Target Page Url  |  Status
-------------  |  -------------  |  -------------  |  -------------  |  -------------
26/11/2020 13:03:14  |  00:00:01  |  []()  |  []()  |  A issue prevented successful transformation
### 26/11/2020 13:03:16 - []()

_The property or field has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.   at Microsoft.SharePoint.Client.ListItem.GetFieldValue(String fieldName)
   at SharePointPnP.Modernization.Framework.Transform.BasePageTransformator.StoreSourcePageInformationToKeep(ListItem sourcePage)
   at SharePointPnP.Modernization.Framework.Publishing.PublishingPageTransformator.Transform(PublishingPageTransformationInformation publishingPageTransformationInformation)_ 

# Individual Page details
## Transformation Details: 

- Report date: 26/11/2020 13:03:14
- Transform duration: 00:00:01
- Transforming from site: https://***.sharepoint.com/news
- Cross-Site transfer mode to site: https://***.com/sites/News01
-  A critical error occurred - transformation did not complete

### Page Transformation Settings

Property  |  Setting
-------------  |  -------------
Engine version   |   1.0.2010.0
Overwrite   |   True
Target Page Name   |   
Target Page Folder   |   
Target Page Folder Overrides Default Folder   |   False
Keep Page Specific Permissions   |   True
Remove Empty Sections And Columns   |   True
Handle Wiki Images And Videos   |   True
Add Table List Image As Image Web Part   |   True
Keep Page Creation Modification Information   |   True
Publish Created Page   |   True
Post As News   |   True
Disable Page Comments   |   False
Skip Url Rewrite   |   False
Skip Default Url Rewrite   |   False
Url Mapping File   |   
Term Mapping File   |   
Skip Term Store Mapping   |   False
Skip User Mapping   |   False
User Mapping File   |   
L D A P Connection String   |   
Skip Telemetry   |   False
### Transformation Operation Details

Date  |  Operation  |  Actions Performed
-------------  |  -------------  |  ------------- 
26/11/2020 13:03:15  |  _Input Validation_  |  _Validation checks complete_
26/11/2020 13:03:15  |  _SharePoint Connection_  |  _Loading client context objects_
26/11/2020 13:03:15  |  _SharePoint Connection_  |  _Loading target client context object_

**Comment by jansenbe** [comment]
@phil-maynard : would it be possible to debug this from your side? When using the latest PnP Framework nuget package you can use our sourcelink support to easily debug this without having to pull down and build the source code. See https://pnp.github.io/pnpcore/using-the-sdk/basics-debug.html on how to configure visual studio to use sourcelink. See https://github.com/pnp/pnpframework/blob/dev/src/lib/PnP.Framework.Modernization.Test/Transform/Publishing/PublishingPageTests.cs#L38 as sample snippet doing a publishing page transformation from code

**Comment by jansenbe** [comment]
@phil-maynard : alternatively you can also force the author/editor information via PowerShell: see https://github.com/pnp/powershell/discussions/158 for some thread on that (we did some changes to make this easier in PS).

If the issue is resolved for you then please let me know so the issue can be closed

**Comment by jansenbe** [comment]
Closing per no activity anymore. If you feel the given guidance is insufficient or there's other input to help resolve the issue then please open a new one with the needed details. Thanks;
