### ISSUE TITLE
AADSTS70011 and System.UnauthorizedAccessException Applying PnP Template

### ISSUE THREAD

**Issue by anthonywhite** [pnp/pnpframework#1080]
Suddenly getting consistent 401 Unauthorised errors from PnP.Framework when applying a template to a new site. Template has worked fine unchanged for many months.

Reproduced in PowerShell 7.4.5 with PnP 2.12.0 using these steps:
- Connect-PnPOnline as SCA using -interactive (use existing browser token in auth popup)
- Set-PnPTraceLog to Debug
- Invoke-PnPTemplate
- PowerShell Progress bar indicates **_Web Settings_** being applied
- New PnP Auth popup appears with this message:

```
AADSTS70011: The provided request must include a 'scope' input parameter.
The provided value for the input parameter 'scope' is not valid.
The scope https://graph.microsoft.com openid profile offline_access is not valid.
The scope format is invalid.
Scope must be in a valid URI form <https://example/scope> or a valid Guid <guid/scope>. 
```
- PowerShell command freezes even if popup error is dismissed
- Trace log has following at the end:

```
pwsh Information: 0 : 2024-10-29 17:39:15.3857	[Web Settings]	[10]	[Debug]	Code execution scope started	0ms	763a7093-be50-448a-a03a-1653f8490350
pwsh Warning: 0 : 2024-10-29 17:39:15.4567	[Web Settings]	[10]	[Information]	Skipping NoCrawl update because the site is configured for noscript.	71ms	763a7093-be50-448a-a03a-1653f8490350
pwsh Warning: 0 : 2024-10-29 17:39:15.4583	[Web Settings]	[10]	[Information]	Skipping master page update because the site is configured for noscript.	72ms	763a7093-be50-448a-a03a-1653f8490350
pwsh Warning: 0 : 2024-10-29 17:39:15.4588	[Web Settings]	[10]	[Information]	Skipping custom master page update because the site is configured for noscript.	73ms	763a7093-be50-448a-a03a-1653f8490350
pwsh Information: 0 : 2024-10-29 17:39:15.5772	[PnP.Framework]	[0]	[Debug]	Cloning context for https://kpmginsightplatformdev-admin.sharepoint.com/	0ms	
pwsh Information: 0 : 2024-10-29 17:39:15.5779	[PnP.Framework]	[0]	[Debug]	Checking for different audience https://kpmginsightplatformdev-admin.sharepoint.com/	0ms	
pwsh Information: 0 : 2024-10-29 17:39:15.5787	[PnP.Framework]	[0]	[Debug]	Setting up context for different audience AzureADInteractive	0ms	
pwsh Information: 0 : 2024-10-29 17:39:15.5803	[GetContextAsync]	[0]	[Debug]	Authentication type: AzureADInteractive for scopes https://kpmginsightplatformdev-admin.sharepoint.com/.default	0ms	
pwsh Error: 0 : 2024-10-29 17:39:16.0788	[PnP.Framework]	[0]	[Error]	ExecuteQuery threw following exception: Microsoft.SharePoint.Client.ServerUnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServerAsync(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
ServerErrorCode: -2147024891
ServerErrorTypeName: System.UnauthorizedAccessException
```

<img width="572" alt="PNPError2" src="https://github.com/user-attachments/assets/35f97f74-ebd3-41d6-8906-b7d1bcad6974">
<img width="623" alt="PNPError1" src="https://github.com/user-attachments/assets/202517e4-c1a8-42ef-b665-728738ac2483">

**Comment by anthonywhite** [comment]
well well, this has disappeared as mysteriously and suddenly as it appeared. Hints from Microsoft that tenant level things were at play. Hope this log may help others.
