### ISSUE TITLE
GetPages Error Property LookupId was not yet loaded

### ISSUE THREAD

**Issue by czullu** [pnp/pnpframework#130]
When i try to export a default Teams-Site as Template i get on home.aspx following error. It used to work with same Site last week so i'm not sure what changed. As i do not see any change in pnpcore and i'm using this test site just for extract template tests it seems ms did some change.

[2021-01-25T15:42:52.947Z] PnP.Core.ClientException: Property LookupId was not yet loaded
[2021-01-25T15:42:52.966Z]    at PnP.Core.Model.SharePoint.FieldValue.GetValue[T](String propertyName)
[2021-01-25T15:42:53.010Z]    at PnP.Core.Model.SharePoint.FieldLookupValue.get_LookupId()
[2021-01-25T15:42:53.027Z]    at PnP.Core.Model.SharePoint.ListDataAsStreamHandler.Deserialize(String json, List list)
[2021-01-25T15:42:53.086Z]    at PnP.Core.Model.SharePoint.List.GetListDataAsStreamAsync(RenderListDataOptions renderOptions)
[2021-01-25T15:42:53.091Z]    at PnP.Core.Model.SharePoint.Page.GetPagesListData(String pageName, IList pagesLibrary)
[2021-01-25T15:42:53.112Z]    at PnP.Core.Model.SharePoint.Page.LoadPagesAsync(PnPContext context, String pageName)
[2021-01-25T15:42:53.129Z]    at PnP.Core.Model.SharePoint.Web.GetPagesAsync(String pageName)
[2021-01-25T15:42:53.153Z]    at PnP.Core.Model.SharePoint.Web.GetPages(String pageName)
[2021-01-25T15:42:53.172Z]    at Microsoft.SharePoint.Client.PageExtensions.LoadClientSidePage(Web web, String pageName) in C:\DEV\Repos\pnpframework\src\lib\PnP.Framework\Extensions\PageExtensions.cs:line 865
[2021-01-25T15:42:53.191Z]    at PnP.Framework.Provisioning.ObjectHandlers.Utilities.ClientSidePageContentsHelper.ExtractClientSidePage(Web web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo, PnPMonitoredScope scope, PageToExport page) in C:\DEV\Repos\pnpframework\src\lib\PnP.Framework\Provisioning\ObjectHandlers\Utilities\ClientSidePageContentsHelper.cs:line 58
[2021-01-25T15:42:53.198Z]    at PnP.Framework.Provisioning.ObjectHandlers.ObjectClientSidePageContents.ExtractObjects(Web web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo) in C:\DEV\Repos\pnpframework\src\lib\PnP.Framework\Provisioning\ObjectHandlers\ObjectClientSidePageContents.cs:line 202
[2021-01-25T15:42:53.208Z]    at PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.GetRemoteTemplate(Web web, ProvisioningTemplateCreationInformation creationInfo) in C:\DEV\Repos\pnpframework\src\lib\PnP.Framework\Provisioning\ObjectHandlers\SiteToTemplateConversion.cs:line 137
[2021-01-25T15:42:53.219Z]    at Microsoft.SharePoint.Client.WebExtensions.GetProvisioningTemplate(Web web, ProvisioningTemplateCreationInformation creationInfo) in C:\DEV\Repos\pnpframework\src\lib\PnP.Framework\Extensions\WebExtensions.cs:line 1207
[2021-01-25T15:42:53.264Z]    at CN365TemplateAPI.Utilities.ProvisioningTemplateHelper.GetTemplate(ClientContext appOnlyCtx, BaseDto baseDto, String siteUrl, SiteInfoDto graphInfoDto, IDurableOrchestrationClient doClient, Handlers activeHandlers, String templateAutor) in C:\DEV\Repos\CN365Services\CN365TemplateAPI\Utilities\ProvisioningTemplateHelper.cs:line 342
[2021-01-25T15:42:53.280Z]    at CN365TemplateAPI.ActivityFunctions.ActivityExtractSite.Run(ExtractSiteDto extractSiteDto, IDurableOrchestrationClient doClient, ILogger logger)

**Comment by jansenbe** [comment]
@czullu : I've fixed this yesterday, cross check you're using version 1.1.5 of PnP Framework.

**Comment by czullu** [comment]
> @czullu : I've fixed this yesterday, cross check you're using version 1.1.5 of PnP Framework.
Can confirm that this is fixed and works again.
