### ISSUE TITLE
Invoke-PnPSiteTemplate: Access denied.

### ISSUE THREAD

**Issue by hermonculous** [pnp/pnpframework#193]
Running Invoke-PnPSiteTemplate to implement a PnP Site Template returns:

Invoke-PnPSiteTemplate: Access denied. You do not have permission to perform this action or access this resource.

Appears to address most template items but Navigation Nodes not  changed.

**Expected behavior**
Execute without issue

**Actual behavior**
Implements site template except:
No template quick launch items
No Page Permissions

**Steps to reproduce behavior**

Connect-PnPOnline https://xxxxxx.sharepoint.com/sites/TestTemplate -PnPManagementShell
Get-PnPSiteTemplate -Out template.xml -IncludeSiteGroups -IncludeAllPages

Connect-PnPOnline https://xxxxxx.sharepoint.com/sites/TemplateInvoke -PnPManagementShell
Invoke-PnPSiteTemplate -Path template.xml -ClearNavigation

_Invoke-PnPSiteTemplate: Access denied. You do not have permission to perform this action or access this resource._

**What is the version of the Cmdlet module you are running?**
Get-Module PnP.PowerShell -ListAvailable | Select-Object Name,Version | Sort-Object Version -Descending

Name           Version
----           -------
PnP.PowerShell 1.3.0
PnP.PowerShell 1.1.0

**Which operating system/environment are you running PnP PowerShell on?**
Windows

**Exception**
Get-PnPException

Message          : Access denied. You do not have permission to perform this action or access this resource.
Stacktrace       :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
                      at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
                      at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServerAsync(ChunkStringBuilder sb)
                      at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryAsync()
                      at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQueryAsync()
                      at Microsoft.SharePoint.Client.ClientContext.ExecuteQueryAsync()
                      at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent) in
                   C:\repos\pnpframework\src\lib\PnP.Framework\Extensions\ClientContextExtensions.cs:line 141
                      at Microsoft.SharePoint.Client.FeatureExtensions.IsFeatureActiveInternal(FeatureCollection features, Guid featureID, Boolean noRetry) in
                   C:\repos\pnpframework\src\lib\PnP.Framework\Extensions\FeatureExtensions.cs:line 194
                      at Microsoft.SharePoint.Client.FeatureExtensions.IsFeatureActive(Web web, Guid featureID) in C:\repos\pnpframework\src\lib\PnP.Framework\Extensions\FeatureExtensions.cs:line 151
                      at Microsoft.SharePoint.Client.SiteExtensions.IsCommunicationSite(Site site) in C:\repos\pnpframework\src\lib\PnP.Framework\Extensions\SiteExtensions.cs:line 88
                      at PnP.Framework.Provisioning.ObjectHandlers.ObjectSiteSettings.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation) in
                   C:\repos\pnpframework\src\lib\PnP.Framework\Provisioning\ObjectHandlers\ObjectSiteSettings.cs:line 77
                      at PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo, Boolean
                   calledFromHierarchy, TokenParser tokenParser) in C:\repos\pnpframework\src\lib\PnP.Framework\Provisioning\ObjectHandlers\SiteToTemplateConversion.cs:line 457
                      at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation) in
                   C:\repos\pnpframework\src\lib\PnP.Framework\Extensions\WebExtensions.cs:line 1182
                      at PnP.PowerShell.Commands.Provisioning.Site.InvokeSiteTemplate.ExecuteCmdlet() in C:\repos\powershell\src\Commands\Provisioning\Site\InvokeSiteTemplate.cs:line 377
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in C:\repos\powershell\src\Commands\Base\PnPSharePointCmdlet.cs:line 90
ScriptLineNumber : 1

**Comment by jansenbe** [comment]
@hermonculous :
Seems like you're still having 2 versions of PnP PowerShell, best to drop the 1.1 version. 

I assume you're account is also Site Collection Admin on the target site?

You can also try commenting our the "Settings" parts of the template and see if that helps

**Comment by hermonculous** [comment]
@jansenbe  Thanks for the response.

Yes was SCA - I also removed version 1.1 but same result.

However, your suggestion of removing the 'Settings' from the template did the trick.
The offending line was:
<pnp:SiteSettings AllowDesigner="true" SearchBoxInNavBar="Inherit" SearchCenterUrl="" /> 

The sites in question (original template site and target site) are both Team Sites (STS#3 without group).  Could this be the source of the issue?

Hoping to create a templating process that will not require editing the template...

**Comment by SteveClements** [comment]
I'm having exactly the same issue with SiteSettings.  Also works fine if I exclude that handler.  I'm also building STS#3 sites.

Why is that?  What is it trying to access that it cannot?  I've tried with an AD App with full control - still the same issue.

**Comment by klaaslauwers** [comment]
Linked issue: https://github.com/pnp/pnpframework/issues/357
May be fixed by pull request https://github.com/pnp/pnpframework/pull/360

**Comment by Stiino0** [comment]
Came here to say that my STS#3 PnP Template also worked by removing the site settings
