### ISSUE TITLE
Get-PnPSiteTemplate returning a method not found error

### ISSUE THREAD

**Issue by alexc-MSFT** [pnp/pnpframework#222]
When running the Get-PnPSiteTemplate cmdlet using the latest 1.4.0 version of the new PnP.PowerShell module I now receive the following error, this was previously working:

`Get-PnPSiteTemplate -Out C:\template.xml -ExcludeHandlers SiteSecurity`

Get-PnPSiteTemplate : Method not found: 'System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1<Boolean>
Enumerator.MoveNextAsync()'.
At line:1 char:1
+ Get-PnPSiteTemplate -Out C:\template.xml -ExcludeHandlers SiteSecurit ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPSiteTemplate], MissingMethodException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Site.GetSiteTemplate

**Comment by jansenbe** [comment]
@alexc-MSFT : Please run Get-PnPException after the error has occurred + let us know which PS version (v5/v7) you're using?

**Comment by whitehotaru** [comment]
Hi! Not OP, but I get the same Error on a Mac and a Windows machine. This output is from my Mac: 
```
PS /Users/username> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```
PS /Users/username> Get-PnPException                                                                                                                                                                                                                                                                                                                                                                                                                                       Message          : An error occurred while sending the request.                                                                                                                                                                        Stacktrace       :    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)                                                                                                                                                                  at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)                                                               --- End of stack trace from previous location ---                                                                                                                                                                                         at Microsoft.SharePoint.Client.SPWebRequestExecutor.ExecuteAsync()
                      at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServerAsync(ChunkStringBuilder sb)
                      at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryAsync()
                      at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQueryAsync()
                      at Microsoft.SharePoint.Client.ClientContext.ExecuteQueryAsync()
                      at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
                      at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
                      at Microsoft.SharePoint.Client.ClientObjectExtensions.EnsurePropertiesImplementation[T](T clientObject, Expression`1[] propertySelector)
                      at Microsoft.SharePoint.Client.ClientObjectExtensions.EnsureProperties[T](T clientObject, Expression`1[] propertySelector)
                      at Microsoft.SharePoint.Client.WebExtensions.GetAppCatalog(Web web)
                      at PnP.Framework.Provisioning.ObjectHandlers.ObjectApplicationLifecycleManagement.ExtractObjects(Web web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo)
                      at PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.GetRemoteTemplate(Web web, ProvisioningTemplateCreationInformation creationInfo)
                      at Microsoft.SharePoint.Client.WebExtensions.GetProvisioningTemplate(Web web, ProvisioningTemplateCreationInformation creationInfo)
                      at PnP.PowerShell.Commands.Provisioning.Site.GetSiteTemplate.ExtractTemplate(XMLPnPSchemaVersion schema, String path, String packageName, ExtractConfiguration configuration) in
                   c:\PnPPowerShell\src\Commands\Provisioning\Site\GetSiteTemplate.cs:line 371
                      at PnP.PowerShell.Commands.Provisioning.Site.GetSiteTemplate.ExecuteCmdlet() in c:\PnPPowerShell\src\Commands\Provisioning\Site\GetSiteTemplate.cs:line 149
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in c:\PnPPowerShell\src\Commands\Base\PnPSharePointCmdlet.cs:line 60
ScriptLineNumber : 1
```

**Comment by whitehotaru** [comment]
Hi! I was able to run the same set of commands on my clients productive tenant. Oddly it worked for most site collections with `Get-PnPSiteTemplate -out Mysitetemplate.xml -IncludeAllPages` execpt a hubsite, where the same command failed with:

```
Message          : Oops...seems we end up here anyway...check PnP.Framework code to understand what was here
Stacktrace       :    at PnP.Core.Model.SharePoint.PageWebPart.FromHtml(IElement element)
                      at PnP.Core.Model.SharePoint.Page.LoadFromHtml(String html, String pageHeaderHtml)
                      at PnP.Core.Model.SharePoint.Page.LoadPageAsync(IList pagesLibrary, IListItem item)
                      at PnP.Core.Model.SharePoint.Page.LoadPagesAsync(PnPContext context, String pageName)
                      at PnP.Core.Model.SharePoint.Web.GetPagesAsync(String pageName)
                      at PnP.Core.Model.SharePoint.Web.GetPages(String pageName)
                      at Microsoft.SharePoint.Client.PageExtensions.LoadClientSidePage(Web web, String pageName)
                      at PnP.Framework.Provisioning.ObjectHandlers.Utilities.ClientSidePageContentsHelper.ExtractClientSidePage(Web web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation
                   creationInfo, PnPMonitoredScope scope, PageToExport page)
                      at PnP.Framework.Provisioning.ObjectHandlers.ObjectClientSidePageContents.ExtractObjects(Web web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo)
                      at PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.GetRemoteTemplate(Web web, ProvisioningTemplateCreationInformation creationInfo)
                      at Microsoft.SharePoint.Client.WebExtensions.GetProvisioningTemplate(Web web, ProvisioningTemplateCreationInformation creationInfo)
                      at PnP.PowerShell.Commands.Provisioning.Site.GetSiteTemplate.ExtractTemplate(XMLPnPSchemaVersion schema, String path, String packageName, ExtractConfiguration configuration) in
                   c:\PnPPowerShell\src\Commands\Provisioning\Site\GetSiteTemplate.cs:line 371
                      at PnP.PowerShell.Commands.Provisioning.Site.GetSiteTemplate.ExecuteCmdlet() in c:\PnPPowerShell\src\Commands\Provisioning\Site\GetSiteTemplate.cs:line 144
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in c:\PnPPowerShell\src\Commands\Base\PnPSharePointCmdlet.cs:line 60
ScriptLineNumber : 1
```

```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by pieronegri** [comment]
I am getting 
`Message          : Method not found: 'System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1<Boolean> Enumerator.MoveNextAsync()'.
Stacktrace       :    at PnP.Core.QueryModel.QueryableExtensions.<ToListAsync>d__15`1.MoveNext()
                      at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
                      at PnP.Core.QueryModel.QueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
                      at PnP.Core.Model.SharePoint.Page.<EnsurePagesLibraryAsync>d__96.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at PnP.Core.Model.SharePoint.Page.<LoadPagesAsync>d__93.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at PnP.Core.Model.SharePoint.Web.<GetPagesAsync>d__282.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at PnP.Core.Model.SharePoint.Web.GetPages(String pageName)
                      at Microsoft.SharePoint.Client.PageExtensions.LoadClientSidePage(Web web, String pageName)
                      at PnP.Framework.Provisioning.ObjectHandlers.Utilities.ClientSidePageContentsHelper.ExtractClientSidePage(Web web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo, 
                   PnPMonitoredScope scope, PageToExport page)
                      at PnP.Framework.Provisioning.ObjectHandlers.ObjectClientSidePageContents.ExtractObjects(Web web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo)
                      at PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.GetRemoteTemplate(Web web, ProvisioningTemplateCreationInformation creationInfo)
                      at PnP.PowerShell.Commands.Provisioning.Site.GetSiteTemplate.ExtractTemplate(XMLPnPSchemaVersion schema, String path, String packageName, ExtractConfiguration configuration)
                      at PnP.PowerShell.Commands.Provisioning.Site.GetSiteTemplate.ExecuteCmdlet()
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()`
it was working yesterday
