### ISSUE TITLE
ConvertTo-PnPPage transformation, Some pages fails with error "_'0x0A' is invalid within a JSON string. The string should be correctly escaped"

### ISSUE THREAD

**Issue by PrasadMadhavan** [pnp/pnpframework#311]
hen I run the above command against some of the pages, it fails with an error _'0x0A' is invalid within a JSON string. The string should be correctly escaped". I haven't noticed presence of any special characters on these pages when compared with the other pages. . Can you please help? I have attached the page transformation report in comments.

The command is given below.
ConvertTo-PnPPage -Identity "PageName.aspx" -PublishingPage -TargetWebUrl https://********sharepoint.com/sites/modernuat/***-OverWrite -PageLayoutMapping "custompagelayoutmapping.xml" -LogType File -LogFolder c:\temp -LogVerbose -ClearCache

**Comment by PrasadMadhavan** [comment]
# Modernization Summary Report

Date  |  Duration  |  Source Page  |  Target Page Url  |  Status
-------------  |  -------------  |  -------------  |  -------------  |  -------------
05/05/2021 15:05:51  |  00:00:27  |  [/***/Pages/p2p2.aspx](https://**********.sharepoint.com/***/Pages/p2p2.aspx)  |  []()  |  A issue prevented successful transformation
## Critical Errors during transformation

### 05/05/2021 15:06:19 - [/***/Pages/p2p2.aspx](https://**********.sharepoint.com/***/Pages/p2p2.aspx)

_'0x0A' is invalid within a JSON string. The string should be correctly escaped. LineNumber: 0 | BytePositionInLine: 84.   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeStringAndValidate(ReadOnlySpan`1 data, Int32 idx)
   at System.Text.Json.Utf8JsonReader.ConsumeString()
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedBytes)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at System.Text.Json.JsonDocument.Parse(String json, JsonDocumentOptions options)
   at PnP.Core.Model.SharePoint.PageWebPart.set_PropertiesJson(String value)
   at PnP.Framework.Modernization.Transform.ContentTransformator.Transform(List`1 webParts)
   at PnP.Framework.Modernization.Publishing.PublishingPageTransformator.Transform(PublishingPageTransformationInformation publishingPageTransformationInformation)_ 

# Individual Page details
## Transformation Details: /***/Pages/p2p2.aspx

- Report date: 05/05/2021 15:05:51
- Transform duration: 00:00:27
- Transforming from site: https://**********.sharepoint.com/***
- Cross-Site transfer mode to site: https://**********.sharepoint.com/sites/modernuat/***
- Transforming page: /***/Pages/p2p2.aspx
- Source SharePoint version:  Online (16.0.0.21221)
- Mode:  Publishing Page Transformation Mode
- An referenced asset was found and copied to: /sites/modernuat/***/SiteAssets/SitePages/2/RACImatrixbutton.jpg
- An referenced asset was found and copied to: /sites/modernuat/***/SiteAssets/SitePages/2/p2pFAQsbutton.jpg
- An referenced asset was found and copied to: /sites/modernuat/***/SiteAssets/SitePages/2/01.jpg
- An referenced asset was found and copied to: /sites/modernuat/***/SiteAssets/SitePages/2/02R.jpg
- An referenced asset was found and copied to: /sites/modernuat/***/SiteAssets/SitePages/2/03.jpg
-  A critical error occurred - transformation did not complete

### Page Transformation Settings

Property  |  Setting
-------------  |  -------------
Engine version   |   1.2.0.0
Overwrite   |   True
Target Page Name   |   
Target Page Folder   |   
Target Page Folder Overrides Default Folder   |   False
Keep Page Specific Permissions   |   True
Remove Empty Sections And Columns   |   True
Handle Wiki Images And Videos   |   True
Add Table List Image As Image Web Part   |   True
Keep Page Creation Modification Information   |   False
Publish Created Page   |   True
Post As News   |   False
Disable Page Comments   |   True
Skip Url Rewrite   |   False
Skip Default Url Rewrite   |   False
Url Mapping File   |   
Term Mapping File   |   
Skip Term Store Mapping   |   False
Skip User Mapping   |   False
User Mapping File   |   
L D A P Connection String   |   
Skip Telemetry   |   False
### Transformation Operation Details

Date  |  Operation  |  Actions Performed
-------------  |  -------------  |  ------------- 
05/05/2021 15:05:52  |  _Input Validation_  |  _Validation checks complete_
05/05/2021 15:05:52  |  _SharePoint Connection_  |  _Loading client context objects_
05/05/2021 15:05:52  |  _SharePoint Connection_  |  _Loading target client context object_
05/05/2021 15:05:52  |  _Page Creation_  |  _Detect if the page is living inside a folder_
05/05/2021 15:05:52  |  Page Creation  |  In Cross-Site transform mode the original source file name is used
05/05/2021 15:05:52  |  _Page Creation_  |  _Just try to load the page in the fastest possible manner, we only want to see if the page exists or not_
05/05/2021 15:05:54  |  Load  |  Page does not exist in current web
05/05/2021 15:05:54  |  Page Creation  |  Checking Page Exists
05/05/2021 15:05:55  |  Page Creation  |  Modern page created 
05/05/2021 15:05:55  |  Article page handling  |  Transforming source page as Article page
05/05/2021 15:05:55  |  Article page handling  |  Recognized source page as a Publishing Page - Analyzing web parts and page layouts
05/05/2021 15:05:55  |  Page Layout Manager  |  Page uses SingleContentWwW as page layout, mapping that will be used is SingleContentWwW
05/05/2021 15:06:03  |  Article page handling  |  Splitting images and videos from wiki text - as modern text web part does not support embedded images and videos
05/05/2021 15:06:03  |  Set Page Title  |  Setting the modern page title: 2. Procurement & Tender
05/05/2021 15:06:03  |  _Article page handling_  |  _Preparing content transformation_
05/05/2021 15:06:03  |  Article page handling  |  Transforming content
05/05/2021 15:06:03  |  Content Transform  |  Transforming web parts
05/05/2021 15:06:08  |  Web Part Mapping  |  Web Part:'WikiText' of type 'SharePointPnP.Modernization.WikiTextPart' is being transformed
05/05/2021 15:06:08  |  _Web Part Mapping_  |  _Processing selector functions_
05/05/2021 15:06:08  |  _Web Part Mapping_  |  _Combining mapping data_
05/05/2021 15:06:08  |  Adding Web Parts to Target Page  |  Added 'Client Side Text Web Part' to target page
05/05/2021 15:06:08  |  Web Part Mapping  |  Web Part:'Wiki text' of type 'SharePointPnP.Modernization.WikiTextPart' is being transformed
05/05/2021 15:06:08  |  _Web Part Mapping_  |  _Processing selector functions_
05/05/2021 15:06:08  |  _Web Part Mapping_  |  _Combining mapping data_
05/05/2021 15:06:08  |  Adding Web Parts to Target Page  |  Added 'Client Side Text Web Part' to target page
05/05/2021 15:06:08  |  Web Part Mapping  |  Web Part:'Image in wiki text' of type 'SharePointPnP.Modernization.WikiImagePart' is being transformed
05/05/2021 15:06:08  |  _Web Part Mapping_  |  _Processing selector functions_
05/05/2021 15:06:10  |  Asset Transfer  |  Uploading RACImatrixbutton.jpg
05/05/2021 15:06:10  |  Asset Transfer  |  Upload RACImatrixbutton.jpg complete
05/05/2021 15:06:10  |  _Web Part Mapping_  |  _Combining mapping data_
05/05/2021 15:06:10  |  Adding Web Parts to Target Page  |  Using 'Image' modern web part
05/05/2021 15:06:10  |  Adding Web Parts to Target Page  |  Added 'Image' Client Side Web Part to target page
05/05/2021 15:06:10  |  Web Part Mapping  |  Web Part:'Wiki text' of type 'SharePointPnP.Modernization.WikiTextPart' is being transformed
05/05/2021 15:06:10  |  _Web Part Mapping_  |  _Processing selector functions_
05/05/2021 15:06:10  |  _Web Part Mapping_  |  _Combining mapping data_
05/05/2021 15:06:10  |  Adding Web Parts to Target Page  |  Added 'Client Side Text Web Part' to target page
05/05/2021 15:06:10  |  Web Part Mapping  |  Web Part:'Image in wiki text' of type 'SharePointPnP.Modernization.WikiImagePart' is being transformed
05/05/2021 15:06:10  |  _Web Part Mapping_  |  _Processing selector functions_
05/05/2021 15:06:12  |  Asset Transfer  |  Uploading p2pFAQsbutton.jpg
05/05/2021 15:06:12  |  Asset Transfer  |  Upload p2pFAQsbutton.jpg complete
05/05/2021 15:06:12  |  _Web Part Mapping_  |  _Combining mapping data_
05/05/2021 15:06:12  |  Adding Web Parts to Target Page  |  Using 'Image' modern web part
05/05/2021 15:06:12  |  Adding Web Parts to Target Page  |  Added 'Image' Client Side Web Part to target page
05/05/2021 15:06:12  |  Web Part Mapping  |  Web Part:'Wiki text' of type 'SharePointPnP.Modernization.WikiTextPart' is being transformed
05/05/2021 15:06:12  |  _Web Part Mapping_  |  _Processing selector functions_
05/05/2021 15:06:12  |  _Web Part Mapping_  |  _Combining mapping data_
05/05/2021 15:06:12  |  Adding Web Parts to Target Page  |  Added 'Client Side Text Web Part' to target page
05/05/2021 15:06:12  |  Web Part Mapping  |  Web Part:'Image in wiki text' of type 'SharePointPnP.Modernization.WikiImagePart' is being transformed
05/05/2021 15:06:12  |  _Web Part Mapping_  |  _Processing selector functions_
05/05/2021 15:06:14  |  Asset Transfer  |  Uploading 01.jpg
05/05/2021 15:06:14  |  Asset Transfer  |  Upload 01.jpg complete
05/05/2021 15:06:14  |  _Web Part Mapping_  |  _Combining mapping data_
05/05/2021 15:06:14  |  Adding Web Parts to Target Page  |  Using 'Image' modern web part
05/05/2021 15:06:14  |  Adding Web Parts to Target Page  |  Added 'Image' Client Side Web Part to target page
05/05/2021 15:06:14  |  Web Part Mapping  |  Web Part:'Wiki text' of type 'SharePointPnP.Modernization.WikiTextPart' is being transformed
05/05/2021 15:06:14  |  _Web Part Mapping_  |  _Processing selector functions_
05/05/2021 15:06:14  |  _Web Part Mapping_  |  _Combining mapping data_
05/05/2021 15:06:14  |  Adding Web Parts to Target Page  |  Added 'Client Side Text Web Part' to target page
05/05/2021 15:06:14  |  Web Part Mapping  |  Web Part:'Image in wiki text' of type 'SharePointPnP.Modernization.WikiImagePart' is being transformed
05/05/2021 15:06:14  |  _Web Part Mapping_  |  _Processing selector functions_
05/05/2021 15:06:16  |  Asset Transfer  |  Uploading 02R.jpg
05/05/2021 15:06:16  |  Asset Transfer  |  Upload 02R.jpg complete
05/05/2021 15:06:16  |  _Web Part Mapping_  |  _Combining mapping data_
05/05/2021 15:06:16  |  Adding Web Parts to Target Page  |  Using 'Image' modern web part
05/05/2021 15:06:16  |  Adding Web Parts to Target Page  |  Added 'Image' Client Side Web Part to target page
05/05/2021 15:06:16  |  Web Part Mapping  |  Web Part:'Wiki text' of type 'SharePointPnP.Modernization.WikiTextPart' is being transformed
05/05/2021 15:06:16  |  _Web Part Mapping_  |  _Processing selector functions_
05/05/2021 15:06:16  |  _Web Part Mapping_  |  _Combining mapping data_
05/05/2021 15:06:16  |  Adding Web Parts to Target Page  |  Added 'Client Side Text Web Part' to target page
05/05/2021 15:06:16  |  Web Part Mapping  |  Web Part:'Image in wiki text' of type 'SharePointPnP.Modernization.WikiImagePart' is being transformed
05/05/2021 15:06:16  |  _Web Part Mapping_  |  _Processing selector functions_
05/05/2021 15:06:18  |  Asset Transfer  |  Uploading 03.jpg
05/05/2021 15:06:18  |  Asset Transfer  |  Upload 03.jpg complete
05/05/2021 15:06:19  |  _Web Part Mapping_  |  _Combining mapping data_
05/05/2021 15:06:19  |  Adding Web Parts to Target Page  |  Using 'Image' modern web part

**Comment by jansenbe** [comment]
@PrasadMadhavan : things go wrong when building the json properties for the modern image web part that will hold 03.jpg.  When an image web part is mapped to a modern image web part the json properties are constructed using this template:

```json
{
    "serverProcessedContent": {
        "htmlStrings": {},
        "searchablePlainTexts": {
            "captionText": "{Caption}"
        },
        "imageSources": {
            "imageSource": "{ServerRelativeFileName}"
        },
        "links": {
            "linkUrl": "{Anchor}"
        }
    },
    "dataVersion": "1.8",
    "properties": {
        "imageSourceType": 2,
        "altText": "{AlternativeText}",
        "fileName": "{FileName}",
        "siteId": "{SiteId}",
        "webId": "{webId}",
        "listId": "{ImageListId}",
        "uniqueId": "{ImageUniqueId}",
        "useParallax": false
    }
}
```

the values within {} are replaced by values received from the source web part, possible candidates for containing some bad characters are {Caption}, {Anchor} or {AlternativeText}. Can you cross that image on the source page and share all the properties of the source image?

**Comment by jansenbe** [comment]
Closing per no activity on this one anymore. I assume it's solved by my answer, if not please create a new issue with the additional information asked in my previous reply.

**Comment by PrasadMadhavan** [comment]
Sorry for the delay in reply. It was indeed some special characters in the HTML. I was not able to figure out which specific one is causing the issue. But I got it working after tidying up HTML on one page. I am yet to try this for remaining pages. 

Thanks a lot for your help.
