### ISSUE TITLE
CSOM - ApplyProvisioningTemplate - Access denied. You do not have permission to perform this action or access this resource.

### ISSUE THREAD

**Issue by asith-w** [pnp/pnpframework#315]
I was using ApplyProvisioningTemplate function and it is **used to work**. but now it gives  following error 
 **`Access denied. You do not have permission to perform this action or access this resource.`**  

I am using SharePoint rest api with '"**AllSites.FullControl AllSites.Manage AllSites.Write User.Read**" scopes

Tested  PnP.Framework versions are 1.3.0 , 1.4.0  

it fails after '**05/14 - Fields**' step when i log the ProgressDelegate event  
 ```
  at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServerAsync(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
   at PnP.Framework.Provisioning.ObjectHandlers.ObjectField.UpdateField(Web web, String fieldId, XElement templateFieldElement, PnPMonitoredScope scope, TokenParser parser, String originalFieldXml)
   at PnP.Framework.Provisioning.ObjectHandlers.ObjectField.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)
   at PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo, Boolean calledFromHierarchy, TokenParser tokenParser)
   at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation)
   at ZAPP.Source.Processors.Z.ApplyTemplate() in D:\Dev\ZAPP-Z\Source\Processors\Z.cs:line 187
   at ZAPP.Source.Processors.Z.Execute() in D:\Dev\ZAPP-Z\Source\Processors\Z.cs:line 41
   
```
   

```
using (var context = new ClientContext(url))
            {
                context.ExecutingWebRequest += delegate (object sender, WebRequestEventArgs e)
                {
                    e.WebRequestExecutor.WebRequest.Headers.Add("Authorization", "Bearer " + sp-rest-accessToken);
                };
                Web web = context.Web;
                context.Load(web, w => w.Title);
                context.ExecuteQueryRetry();

            
                XMLTemplateProvider provider = new XMLFileSystemTemplateProvider(@"Sharepoint/abc", "");
                ProvisioningTemplate template = provider.GetTemplate($"{TemplateId}.xml");

                ProvisioningTemplateApplyingInformation ptai
                    = new ProvisioningTemplateApplyingInformation();
                ptai.ProgressDelegate = delegate (String message, Int32 progress, Int32 total)
                {
                     Log (string.Format("ApplyProvisioningTemplate - Progress{0:00}/{1:00} – {2}", progress, total, message));
                     
                };
                ptai.ClearNavigation = true;

                // Associate file connector for assets
                FileSystemConnector connector = new FileSystemConnector(@"Sharepoint/abc", "");
                template.Connector = connector;
                web.ApplyProvisioningTemplate(template, ptai);

                
            }
 
```

**Comment by asith-w** [comment]
It is failed in following request

POST https://mytenant.sharepoint.com/sites/colombo/_vti_bin/client.svc/ProcessQuery

```
<Request AddExpandoFieldTypeSuffix="true" SchemaVersion="15.0.0.0" LibraryVersion="16.0.0.0" ApplicationName=".NET Library"
	xmlns="http://schemas.microsoft.com/sharepoint/clientquery/2009">
	<Actions>
		<SetProperty Id="1433" ObjectPathId="1429" Name="SchemaXml">
			<Parameter Type="String">&lt;Field ID="{cb19284a-cde7-4570-a980-1dab8bd74470}" Name="_ExtendedDescription" SourceID="http://schemas.microsoft.com/sharepoint/v3" StaticName="_ExtendedDescription" DisplayName="Description" Group="Extended Columns" RichText="TRUE" ShowInEditForm="FALSE" RichTextMode="Compatible" CanToggleHidden="TRUE" Type="Note" Sealed="FALSE" /&gt;</Parameter>
		</SetProperty>
		<Method Name="UpdateAndPushChanges" Id="1434" ObjectPathId="1429">
			<Parameters>
				<Parameter Type="Boolean">true</Parameter>
			</Parameters>
		</Method>
		<Query Id="1435" ObjectPathId="1429">
			<Query SelectAllProperties="false">
				<Properties>
					<Property Name="SchemaXml" ScalarProperty="true" />
					<Property Name="TypeAsString" ScalarProperty="true" />
					<Property Name="DefaultValue" ScalarProperty="true" />
				</Properties>
			</Query>
		</Query>
	</Actions>
	<ObjectPaths>
		<Identity Id="1429" Name="0b31c79f-40f1-0000-9f65-f02d882914e1|740c6a0b-85e2-48a0-a494-e0f1759d4aa7:site:67659e6e-0b21-4707-96fe-c6c9a930a6eb:web:4eb8fa1e-2715-4d73-9180-3d156100f6ca:field:cb19284a-cde7-4570-a980-1dab8bd74470" />
	</ObjectPaths>
</Request>
```

-------------Response ------------------------------


```
[
  {
    "SchemaVersion": "15.0.0.0",
    "LibraryVersion": "16.0.21228.12003",
    "ErrorInfo": {
      "ErrorMessage": "Access denied. You do not have permission to perform this action or access this resource.",
      "ErrorValue": null,
      "TraceCorrelationId": "1631c79f-c081-0000-9f65-ff40bcf317c6",
      "ErrorCode": -2147024891,
      "ErrorTypeName": "System.UnauthorizedAccessException"
    },
    "TraceCorrelationId": "1631c79f-c081-0000-9f65-ff40bcf317c6"
  }
]
```
