### ISSUE TITLE
[BUG] Add-PnPPage throws MissingMethodException

### ISSUE THREAD

**Issue by matsn0w** [pnp/pnpframework#323]
I found this issue using the PnP.PowerShell module.
` 
Initially, when I tried to invoke a site template using `Invoke-PnPSiteTemplate`, I got an `MissingMethodException` over and over again - no matter what I tried. I've been trying multiple scenario's, configurations and parameters.

Then, I discovered that running Add-PnPPage resulted in the same exact error, even in a very basic form:

```powershell
Add-PnPPage -Name "My Page"
```

This is the error I get:

```
Add-PnPPage : Method not found: System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1<Boolean> Enumerator.MoveNextAsync().
At line:1 char:1
+ Add-PnPPage -Name "My Page"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Add-PnPPage], MissingMethodException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Pages.AddPage    
```

I suspect that something in the paging engine is broken. 

Any clues? I'm running the latest stable build, 1.5.0

Thanks in advance and keep up the good work!
matsn0w

**Comment by jansenbe** [comment]
@matsn0w : just tried with the current nightly PS and things work as expected. Are you using this from .NET Framework / PS5 or from .NET Core/.NET 5/ PS7 ? Can you try the latest nightly and see if that works for you as well.

If not, please run Get-PnPException after the error and share the output.

Also ensure no other PS modules are loaded by default, this might be an assembly versioning conflic

**Comment by matsn0w** [comment]
Hi Bert,

Thank you for your fast response!

I'm running on PowerShell 5. 

I've installed the latest nightly (1.5.40) in a Sandbox and tried again... No luck :(
A different error this time:

```powershell
PS C:\Users\WDAGUtilityAccount> Get-PnPClientSidePage -Identity home
Get-PnPClientSidePage : Exception of type 'System.Management.Automation.PSInvalidOperationException' was thrown.
At line:1 char:1
+ Get-PnPClientSidePage -Identity home
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-PnPPage], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,PnP.PowerShell.Commands.Pages.GetPage

PS C:\Users\WDAGUtilityAccount> Get-PnPException
Message          : Exception of type 'System.Management.Automation.PSInvalidOperationException' was thrown.
Stacktrace       :    at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()
                      at System.Management.Automation.CommandProcessor.ProcessRecord()
ScriptLineNumber : 1
```

I found out that the issue pops up on all sorts of 'page interactions', Get-*, Add-*, etc. Both ClientSidePages and normal Pages.

**Comment by jansenbe** [comment]
@matsn0w : this feels like a PS issue, transferring this issue to the PS repo
