### ISSUE TITLE
Provisioning fails with ClientId/ClientSecret authentication (AcsAppOnly) 

### ISSUE THREAD

**Issue by sebastianmattar** [pnp/pnpframework#34]
Hi!

We are using authentication by ClientId/ClientSecret. This causes some problems when using site provisioning for some object types (e.g. "SiteHeader") as access token generation is not working in all cases. 
I am looking into fixing it and supplying a pull request.

**Comment by jansenbe** [comment]
Thanks for reporting this @sebastianmattar , looking forward for more details and a possible fix

**Comment by luizfef06** [comment]
@sebastianmattar I am getting a SocketException at  PnP.Framework.Utilities.TokenHelper.AcsMetadataParser.GetMetadataDocument(String realm). Is it the same issue you are facing?

**Comment by luizfef06** [comment]
This is the stack for me:

System.Net.WebException: An invalid argument was supplied. An invalid argument was supplied.
 ---> System.Net.Http.HttpRequestException: An invalid argument was supplied.
 ---> System.Net.Sockets.SocketException (10022): An invalid argument was supplied.
   at System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
   at System.Net.Sockets.DualSocketMultipleConnectAsync..ctor(SocketType socketType, ProtocolType protocolType)
   at System.Net.Sockets.Socket.ConnectAsync(SocketType socketType, ProtocolType protocolType, SocketAsyncEventArgs e)
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at System.Net.WebClient.DownloadData(String address)
   at PnP.Framework.Utilities.TokenHelper.AcsMetadataParser.GetMetadataDocument(String realm)
   at PnP.Framework.Utilities.TokenHelper.AcsMetadataParser.GetStsUrl(String realm)
   at PnP.Framework.Utilities.TokenHelper.GetAppOnlyAccessToken(String targetPrincipalName, String targetHost, String targetRealm)
   at PnP.Framework.AuthenticationManager.ACSEnsureToken(String siteUrl, String realm, String appId, String appSecret, String acsHostUrl, String globalEndPointPrefix)
   at PnP.Framework.AuthenticationManager.GetACSAppOnlyContext(String siteUrl, String realm, String appId, String appSecret, String acsHostUrl, String globalEndPointPrefix)
   at PnP.Framework.AuthenticationManager.GetACSAppOnlyContext(String siteUrl, String appId, String appSecret)

I am working on moving some code from the old library to this new one. Calls to GetAppOnlyAuthenticatedContext using the same url, appId and appSecret are still working.

**Comment by gautamdsheth** [comment]
If you are testing this one newer tenants, you need to execute below command first:

`Set-PnPTenant -DisableCustomAppAuthentication $false`

After 5-10 mins, your code to connect using clientid/clientsecret should start executing.

Reference - https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs

https://www.koskila.net/literally-breaking-changes-to-app-authentication-on-sharepoint-%F0%9F%98%B5/

**Comment by jansenbe** [comment]
Closing as #41 has been merged
