### ISSUE TITLE
ConvertTo-PnPClientSidePage on classic publishing page is not working

### ISSUE THREAD

**Issue by pgupta-mc** [pnp/pnpframework#349]
Command:

ConvertTo-PnPClientSidePage -Identity "testtag44.aspx" -PublishingPage -TargetWebUrl https://contoso.sharepoint.com/sites/pg_cs2 -Overwrite -CopyPageMetadata 

Summary report :

# Modernization Summary Report

Date  |  Duration  |  Source Page  |  Target Page Url  |  Status
-------------  |  -------------  |  -------------  |  -------------  |  -------------
25-05-2021 19:47:55  |  00:00:09  |  [/about/Pages/OrgAnnouncements/testtag44.aspx](https://contoso.sharepoint.com/sites/news/abouc/Pages/OrgAnnouncements/testtag44.aspx)  |  []()  |  A issue prevented successful transformation
### 25-05-2021 19:48:04 - [/about/Pages/OrgAnnouncements/testtag44.aspx](https://contoso.sharepoint.com/sites/news/about/Pages/OrgAnnouncements/testtag44.aspx)

_Requested value 'MonthSpelled' was not found.   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at PnP.Core.Services.JsonMappingHelper.GetJsonFieldValue(IDataModelWithContext pnpObject, String fieldName, JsonElement jsonElement, Type propertyType, Boolean useCustomMapping, Func`2 fromJsonCasting)
   at PnP.Core.Services.JsonMappingHelper.<FromJsonRest>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Services.JsonMappingHelper.<FromJson>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Model.BaseDataModel`1.<ProcessResponseAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PnP.Core.Services.JsonMappingHelper.<FromJsonRest>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Services.JsonMappingHelper.<FromJson>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Model.BaseDataModel`1.<ProcessResponseAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PnP.Core.Services.JsonMappingHelper.<FromJsonRest>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Services.JsonMappingHelper.<FromJson>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Services.JsonMappingHelper.<MapJsonToModel>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PnP.Core.Services.BatchClient.<ProcessSharePointRestBatchResponse>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PnP.Core.Services.BatchClient.<ExecuteSharePointRestBatchAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PnP.Core.Services.BatchClient.<ExecuteBatch>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Services.PnPContext.<ExecuteAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.QueryModel.DataModelQueryService`1.<ExecuteQueryAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.QueryModel.BaseQueryProvider.<GetAsyncEnumerable>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at PnP.Core.QueryModel.QueryableExtensions.<ToListAsync>d__15`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PnP.Core.QueryModel.QueryableExtensions.<ToListAsync>d__15`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Model.SharePoint.Page.<EnsurePagesLibraryAsync>d__96.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Model.SharePoint.Page.<NewPageAsync>d__95.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Model.SharePoint.Web.<NewPageAsync>d__284.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Model.SharePoint.Web.NewPage(PageLayoutType pageLayoutType)
   at Microsoft.SharePoint.Client.PageExtensions.AddClientSidePage(Web web, String pageName, Boolean alreadyPersist)
   at PnP.Framework.Modernization.Publishing.PublishingPageTransformator.Transform(PublishingPageTransformationInformation publishingPageTransformationInformation)_ 

# Individual Page details
## Transformation Details: /about/Pages/OrgAnnouncements/testtag44.aspx

- Report date: 25-05-2021 19:47:55
- Transform duration: 00:00:09
- Transforming from site: https://contoso.sharepoint.com/sites/news/about
- Cross-Site transfer mode to site: https://contoso.sharepoint.com/sites/pg_cs2
- Transforming page: /sites/news/about/Pages/OrgAnnouncements/testtag44.aspx
- Source SharePoint version:  Online (16.0.0.21312)
- Mode:  Publishing Page Transformation Mode
-  A critical error occurred - transformation did not complete

### Page Transformation Settings

Property  |  Setting
-------------  |  -------------
Engine version   |   1.4.0.0
Overwrite   |   True
Target Page Name   |   
Target Page Folder   |   
Target Page Folder Overrides Default Folder   |   False
Keep Page Specific Permissions   |   True
Remove Empty Sections And Columns   |   True
Handle Wiki Images And Videos   |   True
Add Table List Image As Image Web Part   |   True
Keep Page Creation Modification Information   |   True
Publish Created Page   |   True
Post As News   |   False
Disable Page Comments   |   False
Skip Url Rewrite   |   False
Skip Default Url Rewrite   |   False
Url Mapping File   |   
Skip Hidden Web Parts   |   False
Term Mapping File   |   
Skip Term Store Mapping   |   False
Skip User Mapping   |   False
User Mapping File   |   
L D A P Connection String   |   
Skip Telemetry   |   False
### Transformation Operation Details

Date  |  Operation  |  Actions Performed
-------------  |  -------------  |  ------------- 
25-05-2021 19:47:55  |  _Input Validation_  |  _Validation checks complete_
25-05-2021 19:47:55  |  _SharePoint Connection_  |  _Loading client context objects_
25-05-2021 19:47:56  |  _SharePoint Connection_  |  _Loading target client context object_
25-05-2021 19:47:59  |  _Page Creation_  |  _Detect if the page is living inside a folder_
25-05-2021 19:47:59  |  Page Creation  |  The transform page is located in a folder
25-05-2021 19:47:59  |  Page Creation  |  In Cross-Site transform mode the original source file name is used
25-05-2021 19:47:59  |  _Page Creation_  |  _Just try to load the page in the fastest possible manner, we only want to see if the page exists or not_
25-05-2021 19:48:02  |  Load  |  Page does not exist in current web
25-05-2021 19:48:02  |  Page Creation  |  Checking Page Exists

**Comment by pgupta-mc** [comment]
Error : 
Requested value 'MonthSpelled' was not found

**Comment by jansenbe** [comment]
@pgupta-mc : for publishing pages you need to define the metadata fields to copy in your page layout mapping: see https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-model-publishing#pagelayout-definition-in-the-page-layout-model for more details

**Comment by pgupta-mc** [comment]
@jansenbe : Thanks for prompt response and sharing the guideline.

I have tried it with custom layout mapping file and it still shows the same error . Looks like it is trying to use some  enum during conversion and failing because it is not present. 

I saw this [article ](https://techcommunity.microsoft.com/t5/microsoft-365-pnp-blog/improving-the-page-properties-web-part/ba-p/2256651) where MonthSpelled is used to show modern page properties. Am I missing something ?

**Comment by jansenbe** [comment]
@pgupta-mc , really weird...Do you get the same when you leave out the  -CopyPageMetadata option? What type of site collection is the target site? A communication site?

**Comment by pgupta-mc** [comment]
@jansenbe  , yes destination is communication site and I get the same error when I leave out -CopyPageMetadata option

**Comment by pgupta-mc** [comment]
@jansenbe : Issue was related to the specific site. Very weird but when I setup and changed the target site it started working. 

I am closing the issue for now. Thanks for your help !!!
