### ISSUE TITLE
Get-PnPSiteTemplate : File Not Found.

### ISSUE THREAD

**Issue by andikrueger** [pnp/pnpframework#469]
Currently I do see a strange error, when exporting a template. I'm facing a file not found error. The file should be created by PnP.

```powershell
PS C:\temp> Get-PnPSiteTemplate -Connection $sourceConnection -Out template.pnp
Get-PnPSiteTemplate : File Not Found.
At line:1 char:1
+ Get-PnPSiteTemplate -Connection $sourceConnection -Out template.pnp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPSiteTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Site.GetSiteTemplate
PS C:\temp> Get-PnPException


Message          : File Not Found.
Stacktrace       :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
                      at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
                      at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__53.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__39.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__65.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at                                                                                                                   Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__6.MoveNext()                         --- End of stack trace from previous location where exception was thrown ---                                               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()                                                       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)                       at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext                        clientContext, Int32 retryCount, String userAgent)                                                                         at PnP.Framework.Provisioning.ObjectHandlers.ObjectWebSettings.PersistFile(Web web,                                  ProvisioningTemplateCreationInformation creationInfo, PnPMonitoredScope scope, String
                   serverRelativeUrl)
                      at PnP.Framework.Provisioning.ObjectHandlers.ObjectWebSettings.ExtractObjects(Web web,
                   ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo)
                      at PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.GetRemoteTemplate(Web web,
                   ProvisioningTemplateCreationInformation creationInfo)
                      at PnP.PowerShell.Commands.Provisioning.Site.GetSiteTemplate.ExtractTemplate(XMLPnPSchemaVersion
                   schema, String path, String packageName, ExtractConfiguration configuration)
                      at PnP.PowerShell.Commands.Provisioning.Site.GetSiteTemplate.ExecuteCmdlet()
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()
ScriptLineNumber : 1
```

Is there any fix available?

```powershell
PS C:\temp> get-module pnp.powershell

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.7.0      PnP.PowerShell                      {Add-PnPAlert, Add-PnPApp, Add-PnPApplicationCustomizer, A..
```

**Comment by andikrueger** [comment]
Closing this issue, as it is a pnp.powershell issue.
