### ISSUE TITLE
ConvertTo-PnPPage transformation issue

### ISSUE THREAD

**Issue by Sharepoint2k22** [pnp/pnpframework#623]
**### Reporting an Issue**

Using PnP v 1.9.0 (PowerShell v 7.2.1) to convert an on-prem SharePoint 2013 publishing page to modern page in SPO.  This fails reporting "ConvertTo-PnPPage: No digest found!".  The actual command is as follows:

ConvertTo-PnPPage -Identity "pagename.aspx" -PublishingPage -TargetConnection $target -Connection $source

**Expected behaviour**

Classic page transformed/migrated to Site Pages library in modern communication site

**Actual behaviour**

"ConvertTo-PnPPage: No digest found!" message is displayed, Get-PnPException displays the following:

Message          : No digest found!
Stacktrace       :    at Microsoft.SharePoint.Client.ClientContextExtensions.GetOnPremisesRequestDigestInfoAsync(Client
                   Context context)
                      at
                   Microsoft.SharePoint.Client.ClientContextExtensions.GetOnPremisesRequestDigestAsync(ClientContext
                   context)
                      at PnP.Framework.AuthenticationManager.<>c.<ConfigureOnPremisesContext>b__69_0(Object sender,
                   WebRequestEventArgs webRequestEventArgs)
                      at Microsoft.SharePoint.Client.ClientRuntimeContext.OnExecutingWebRequest(WebRequestEventArgs
                   args)
                      at
                   Microsoft.SharePoint.Client.ClientRuntimeContext.FireExecutingWebRequestEvent(WebRequestEventArgs
                   args)
                      at Microsoft.SharePoint.Client.ClientRequest.SetupServerQuery(ChunkStringBuilder sb)
                      at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServerAsync(ChunkStringBuilder sb)
                      at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryAsync()
                      at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQueryAsync()
                      at Microsoft.SharePoint.Client.ClientContext.ExecuteQueryAsync()
                      at
                   Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext
                   clientContext, Int32 retryCount, String userAgent)
                      at Microsoft.SharePoint.Client.ClientObjectExtensions.EnsurePropertyImplementation[T,TResult](T
                   clientObject, Expression`1 propertySelector)
                      at Microsoft.SharePoint.Client.ClientObjectExtensions.EnsureProperty[T,TResult](T clientObject,
                   Expression`1 propertySelector)
                      at PnP.Framework.Modernization.Cache.CacheManager.GetPublishingPagesLibraryName(ClientContext
                   context)
                      at PnP.PowerShell.Commands.Pages.ConvertToClientSidePage.ExecuteCmdlet() in
                   c:\build\src\Commands\Pages\ConvertToPage.cs:line 176
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in
                   c:\build\src\Commands\Base\PnPSharePointCmdlet.cs:line 60
ScriptLineNumber : 1

**Steps to reproduce behaviour**

```
$target = Connect-PnPOnline https://domain.sharepoint.com/sites/site -ReturnConnection
$source = Connect-PnPOnline http://sourcesite -Credentials (Get-Credential) -ReturnConnection -TransformationOnPrem
ConvertTo-PnPPage -Identity "pagename.aspx" -PublishingPage -TargetConnection $target -Connection $source
```

**PowerShell versions**

PnP.Powershell 1.9.0, PowerShell 7.2.1

**Operating system**

Windows 10, version 1809 (OS Build 17763.379)

**Comment by jansenbe** [comment]
@Sharepoint2k22 : when you connect to the on-premises SharePoint using PnP PowerShell do then basic PS cmdlets like `Get-PnPWeb` work? If you've a more special auth setup in on-premises things might not work as expected

**Comment by Sharepoint2k22** [comment]
@jansenbe Many thanks for your answer

To add some additional detail from yesterdays investigation, the environment uses a web proxy and so it looks like this may be the issue.  

The behaviour is somewhat intermittent however as we did manage to get the conversion to work on some occasions yesterday (albeit with varying results on some tests).

We will try your suggestion, but feel the problem is environmental and so will now close this question.

Thanks again.
