### ISSUE TITLE
Socket exception when calling ClientContext ExecuteQuery

### ISSUE THREAD

**Issue by Kizlyk** [pnp/pnpframework#633]
Hello, 

We have switched to PnP.Framework from the old SharePointPnPCoreOnline library, and now we have a new issue that appears only rarely but consistently in many different places. There were no such issues with the old library.

Everytime it happened was when we called the ClientContext ExecuteQuery() method. The exception error is "The system detected an invalid pointer address in attempting to use a pointer argument in a call". Please see the example stack trace below.

Does anybody know what might be the problem? Thank you in advance.

Stack trace:

Core.Exceptions.BikubeRequestFailedException: Unexpected error while executing request GetDocumentByIdQuery
 ---> System.Net.WebException: The system detected an invalid pointer address in attempting to use a pointer argument in a call. [::ffff:40.108.168.41]:443 (asplanviak.sharepoint.com:443)
 ---> System.Net.Http.HttpRequestException: The system detected an invalid pointer address in attempting to use a pointer argument in a call. [::ffff:40.108.168.41]:443 (asplanviak.sharepoint.com:443)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10014): The system detected an invalid pointer address in attempting to use a pointer argument in a call. [::ffff:40.108.168.41]:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
--- End of stack trace from previous location ---
   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
   at System.Net.Sockets.Socket.Connect(String host, Int32 port)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Http.ConnectHelper.Connect(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.Connect(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DelegatingHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClientHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.HttpWebRequest.SendRequest(Boolean async)
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.SharePoint.Client.SPWebRequestExecutor.Execute()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at DocumentService.Infrastructure.Repositories.ListRepository..ctor(ClientContext ctx, String listName) in D:\a\1\s\DocumentService.Infrastructure\Repositories\ListRepository.cs:line 32

**Comment by patrikhellgren** [comment]
Where are you running this code? In the stack trace I notice that the tenant url is resolved to what looks like an IPv4-mapped IPv6 address and I don't recall seeing that before.

To get some better handling of SocketExceptions and possibly better error messages you could try the following:

Since ClientContext.ExecuteQuery() is the out-of-the-box method and doesn't use any of the PnP.Framework logic you could first try using ClientContext.ExecuteQueryRetry() or ClientContext.ExecuteQueryRetryAsync() instead to have a more robust request handling.

You could also try using ```HttpClientWebRequestExecutorFactory``` that uses ```HttpClient``` instead of ```HttpWebRequest``` which also makes the request handling more robust.

Example of usage:
```CSHARP
var authManager = new AuthenticationManager(clientId, certificate, tenantId);
var clientContext = await authManager.GetContextAsync(siteUrl);
clientContext.WebRequestExecutorFactory = new HttpClientWebRequestExecutorFactory(PnPHttpClient.Instance.GetHttpClient());
clientContext.Load(clientContext.Web, w => w.Title);
await clientContext.ExecuteQueryRetryAsync();
Console.WriteLine($"{i} - {clientContext.Web.Title}");
```

**Comment by Kizlyk** [comment]
This is running on azure app service and connecting to sharepoint online.

I'll try your solution, thank you. Since this error only appears only sometimes (once a week or so) it's hard to say right away if the fix works or not.

**Comment by Kizlyk** [comment]
The problem seem to be fixed after changes suggested by @patrikhellgren. Thanks again!
