### ISSUE TITLE
TeamSiteCollectionCreationInformation creation failed with GetACSAppOnlyContext

### ISSUE THREAD

**Issue by ayoubelasryRoot** [pnp/pnpframework#723]
(I saw similar issues created but they were closed without any mitigation)

I'm facing an issue when trying to create TeamSite with PnP using the code below:
 
`
using (ClientContext cc = new AuthenticationManager().GetACSAppOnlyContext(siteUrl, clientID, clientSecret))
{
    var result = await cc.CreateSiteAsync(new TeamSiteCollectionCreationInformation
    {
        Alias = "mymodernteamsite", // Mandatory
        DisplayName = "displayName", // Mandatory
        Description = "description", // Optional
        IsPublic = true, // Optional, default true
    });
}
`

Exception:
System.Exception: App-Only is currently not supported, unless you provide a Microsoft Graph Access Token.
   at PnP.Framework.Sites.SiteCollection.CreateAsync(ClientContext clientContext, TeamSiteCollectionCreationInformation siteCollectionCreationInformation, Int32 delayAfterCreation, Int32 maxRetryCount, Int32 retryDelay, Boolean noWait, String graphAccessToken, AzureEnvironment azureEnvironment)
   at Microsoft.SharePoint.Client.ClientContextExtensions.CreateSiteAsync(ClientContext clientContext, TeamSiteCollectionCreationInformation siteCollectionCreationInformation)
   at VnextApi.SharePointUtils.CreateSite(String siteName) in C:\Users\ayelasr\source\repos\VnextApi\VnextApi\SharePointUtils.cs:line 86
   at VnextApi.Controllers.ProvisioningController.CreateSite() in C:\Users\ayelasr\source\repos\VnextApi\VnextApi\Controllers\ProvisioningController.cs:line 49
   at lambda_method(Closure , Object )

Version: 
"PnP.Framework" Version="1.9.0"
netcoreapp3.1

**Comment by Ofer-Gal** [comment]
Same here  how do you provide the access token?
Version:
"PnP.Framework" Version="1.11.0"
.NET 7
