### ISSUE TITLE
401 Error When Invoking ExecuteQuery() Method

### ISSUE THREAD

**Issue by bishopdave2000** [pnp/pnpframework#730]
I'm writing a console application to populate a Sharepoint Online list, but I keep receiving a 401 error whenever I invoke ClientContext.ExecuteQuery() method.  Can someone tell me what I'm doing incorrectly?  Thanks in advance.

**.Net 6 Code**

`using Microsoft.SharePoint.Client;
using PnP.Framework;

 var authManager = new AuthenticationManager("client-id-guid", "mycert.pfx", "certificate-password",
     "tenant-id-guid");
var result = authManager.GetContext("https://myco.sharepoint.com/sites/custom-site");

result.ExecuteQuery();`

**Azure AD Application API Permissions**

![image](https://user-images.githubusercontent.com/101539/190008296-aa9ad021-210e-47ba-abe3-38db55ac6e6e.png)

**Exception Stack**

System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.SharePoint.Client.SPWebRequestExecutor.Execute()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Program.<Main>$(String[] args) in /RiderProjects/ConsoleApp1/ConsoleApp1/Program.cs:line 11

**Comment by bishopdave2000** [comment]
My issue was related to api permission.
