### ISSUE TITLE
Unhandled "429" response causing damage which requires manual interaction

### ISSUE THREAD

**Issue by fzbm** [pnp/pnpframework#779]
### Reporting an Issue or Missing Feature

Unhandled `429 Too Many Requests` responses can cause damage which requires a manual interaction.

### Expected behavior

PnP should handle `429 Too Many Requests` responses on every CSOM call it makes.

### Actual behavior

We encountered a problem during an automatic and unattended deployment of a template where a site was "damaged" in a way, that a manual interaction was required to fix it.

What happened is, that during the deployment a `429` was returned by SharePoint and was not handled by PnP. This happened during the deployment of a client side page, which led to an incomplete creation and a subsequent error on every retry, because a `NullReferenceException` occurred every time PnP tried to clear the page.

We narrowed the problem down to the `GetAccessToken` method of `ClientContextExtensions` class, which uses `ExecuteQuery` instead of `ExecuteQueryRetry`: https://github.com/pnp/pnpframework/blob/cb85e64617575157ac2becbacaef8635734a9561/src/lib/PnP.Framework/Extensions/ClientContextExtensions.cs#L677-L681

```csharp
System.Net.WebException: The remote server returned an error: (429).
   at System.Net.HttpWebRequest.GetResponse()
   at ...WebRequestExecutor.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at ...WebRequestExecutor.Execute()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContextExtensions.GetAccessToken(ClientRuntimeContext clientContext)
   at PnP.Framework.PnPCoreSdkAuthenticationProvider.GetAccessToken(Uri resource)
   at PnP.Framework.PnPCoreSdkAuthenticationProvider.<GetAccessTokenAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
...
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Model.SharePoint.Page.Save(String pageName)
   at PnP.Framework.Provisioning.ObjectHandlers.ObjectClientSidePages.PreCreatePage(Web web, ProvisioningTemplate template, TokenParser parser, BaseClientSidePage clientSidePage, String pagesLibrary, List pagesLibraryList, Int32& currentPageIndex)
   at PnP.Framework.Provisioning.ObjectHandlers.ObjectClientSidePages.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)
   at PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo, Boolean calledFromHierarchy, TokenParser tokenParser)
...
```

Is there a reason why the method does not use the `Retry` version of `ExecuteQuery`, or is this just an oversight during the development?

I have not tested it yet, but might be retrying the request not possible because there is no actual CSOM request to retry? It looks like until about two years ago there was an `ExecuteQueryRetry`, but was changed back to `ExecuteQuery`: https://github.com/pnp/pnpframework/commit/9a0a81d123bd4f493991888e1d198775b77df4ce#diff-8c55668da13cf6a0da1de3ec7106090088c04f99194e640f82ac64c92c6a5c12L520

A possible workaround would be to set `PnPProvisioningContext.Current` and provide callbacks to retrieve a token. This would prevent the `GetAccessToken` extension method to execute the anonymous query.

I can provide a pull request if desired to change the line to `ExecuteQueryRetry`.

### Steps to reproduce behavior

Hard or not possible to reproduce reliably.

### Which operating system/environment are you running PnP on?

An Azure App Service using a Windows App Service Plan.

**Comment by patrikhellgren** [comment]
Hi @fzbm, since ExecuteQueryRetry does its own replacement of ExecutingWebRequest, GetAccessToken will not succeed in getting the access token from the authorization header if the call to ```ExecuteQuery``` was replaced with ```ExecuteQueryRetry```. The same retry handling as ```ExecuteQueryImplementation``` does could of course be implemented in GetAccessToken. Another option (imo always the best option) would be to use ```HttpClientWebRequestExecutorFactory``` when you initially create the client context that you use in your code. Then you can use PnPHttpClient like below and this has built in retry handling for e.g. 429 errors. You could also use your own HttpClient with this if you wanted more configurable error handling using for example Polly. Another benefit would be that you will never run into port exhaustion during provisioning if you use HttpClient correctly. There is no way of accomplishing this using the default WebRequestExecutorFactory.

Example of usage:
```C#
var authManager = new AuthenticationManager(clientId, certificate, tenantId);
var clientContext = await authManager.GetContextAsync(siteUrl);
clientContext.WebRequestExecutorFactory = new HttpClientWebRequestExecutorFactory(PnPHttpClient.Instance.GetHttpClient());
clientContext.Load(clientContext.Web, w => w.Title);
await clientContext.ExecuteQueryRetryAsync();
Console.WriteLine($"{i} - {clientContext.Web.Title}");
```

**Comment by fzbm** [comment]
Hi @patrikhellgren,

thanks for your fast response. I understand the reason why `ExecuteQueryRetry` is not used.

It looks like the `HttpClientWebRequestExecutorFactory` slipped past me. I think we will use this in conjunction with a non-PnP `HttpClient`, because `PnPHttpClient` uses an own instance of an `IServiceProvider` and our application already provides one. I have not decided yet if we want to reuse the PnP `RetryHandler` or Polly.

I will close the issue.
