### ISSUE TITLE
The JSON value could not be converted to System.Int32.

### ISSUE THREAD

**Issue by yetao** [pnp/pnpframework#787]
Hello,

I'm having the following issue when trying to run the following command over an specific site:

Get-PnPSiteTemplate -Connection $connection -Out $output -Encoding ([System.Text.Encoding]::UTF8) -IncludeAllPages -IncludeAllTermGroups -IncludeNativePublishingFiles -IncludeSearchConfiguration -PersistBrandingFiles -PersistPublishingFiles -Force

Everything goes normal until I get this error in debug output:
Extracting Template from https://n36j.sharepoint.com/sites/S… [Client Side Page Contents                             ]	81167717-0a13-41cc-9b59-8cd7924a2669
Get-PnPSiteTemplate: /tmp/regress/bin/M365-SP-Backup-Site.ps1:53                                                        ed1677172292ms4181167717-0a13-41cc-9b59-8cd7924a2669
Line |                                                                                                                  81167717-0a13-41cc-9b59-8cd7924a2669b59-8cd7924a2669
  53 |      Get-PnPSiteTemplate -Connection $connection -Out $output -Encodin …                                         
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                           
     | The JSON value could not be converted to System.Int32. Path: $.position.sectionIndex | LineNumber: 0 | BytePositionInLine: 107.

This is happening using PnP.Powershell in latest version (1.11.0), but also in the most recent nightly (1.11.124-nightly). I'm opening the issue here as it's what they suggest in their git repo:
...
1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
...

How could I investigate further this problem?

Thanks for any help.
Best regards,
Jorge

**Comment by plamber** [comment]
Hello,
I noticed the same error. I narrowed it down to these commands Get-PnPSiteTemplate .\template.pnp -Handlers Pages,PageContents -IncludeAllClientSidePages -PersistBrandingFiles -Debug. The CSOM code to reproduce it is
```
ProvisioningTemplateCreationInformation creationInformation = new ProvisioningTemplateCreationInformation(context.Web);
creationInformation.PersistPublishingFiles = true;
creationInformation.IncludeAllClientSidePages = true;
creationInformation.HandlersToProcess = handlers;
context.Web.GetProvisioningTemplate(creationInformation);
```

The PageContents handler fails for certain pages. You can validate it by following these steps on a communication site:
- Create a communication site
- Apply the site template "Leadership connection"
- Run the PowerShell script above or the CSOM code above
- It will fail for the page "Contoso-Leadership.aspx" with the error The JSON value could not be converted to System.Int32

**Comment by plamber** [comment]
This issue seems to be related https://github.com/pnp/pnpframework/issues/743

**Comment by PedroMordeP** [comment]
I also have this issue for **Spacer** and/or **Divider** collecting a template with PnP PowerShell
After removing all of them from the pages I could collect the pages.
Not sure what is been done with the properties of the CanvasControl but the issue is

```
The JSON value could not be converted to System.Int32. Path: $.position.sectionIndex | LineNumber: 0 | BytePositionInLine: 107.
STACKTRACE:    at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at PnP.Core.Model.SharePoint.CanvasControl.GetType(String controlDataJson)
   at PnP.Core.Model.SharePoint.Page.LoadFromHtml(String html, String pageHeaderHtml)
   at PnP.Core.Model.SharePoint.Page.<LoadPageAsync>d__126.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PnP.Core.Model.SharePoint.Page.<LoadPagesAsync>d__98.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Model.SharePoint.Web.<GetPagesAsync>d__296.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.PageExtensions.<LoadClientSidePageAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.PageExtensions.LoadClientSidePage(Web web, String pageName)
   at PnP.Framework.Provisioning.ObjectHandlers.Utilities.ClientSidePageContentsHelper.ExtractClientSidePage(Web web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo, PnPMonitoredScope scope, PageToExport page)
   at PnP.Framework.Provisioning.ObjectHandlers.ObjectClientSidePageContents.ExtractObjects(Web web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo)
   at PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.GetRemoteTemplate(Web web, ProvisioningTemplateCreationInformation creationInfo)
   at PnP.PowerShell.Commands.Provisioning.Site.GetSiteTemplate.ExtractTemplate(XMLPnPSchemaVersion schema, String path, String packageName, ExtractConfiguration configuration)
   at PnP.PowerShell.Commands.Provisioning.Site.GetSiteTemplate.ExecuteCmdlet()
   at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()
```

**Comment by vinaunder** [comment]
Any news about this problem?

**Comment by PedroMordeP** [comment]
I think this is resolved on the PnP.Core in version 1.9, just update the references to this version

https://github.com/pnp/pnpcore/pull/1058
