### ISSUE TITLE
Template previously worked, now encounters error "You are not allowed to rename this library."

### ISSUE THREAD

**Issue by mpowney** [pnp/pnpframework#803]
Using PnP.PowerShell to apply a site template, the .pnp template is based on a SharePoint Team site with the following additions:
* A series of custom site columns
* 2x Custom content types
* Custom list
* Custom document library

The Custom document library has a custom content type added, and the default "Document" content type is removed

When executing ```Invoke-PnPSiteTemplate``` with this library, prior to last week, the template would successfully provision to the target site / tenant without crashing out.

As of now, the same .pnp template crashes out immediately after the following debug message is output:

```
pwsh Information: 0 : 2022-12-02 13:30:58.1147  [List instances]        [10]    [Debug] Added property bag entry IsAttachmentLibrary to list Committee Documents        37731ms 4f001375-60b0-46f1-a95b-ce7beb954e8a
```

The same error above can be reproduced with the same .pnp template in two tenants.

The same .pnp template continues to work in a different tenant (a developer tenant on first release)

Exception:

```
pwsh Error: 0 : 2022-12-02 13:30:58.3094        [PnP.Framework] [0]     [Error] ExecuteQuery threw following exception: Microsoft.SharePoint.Client.ServerException: You are not allowed to rename this library.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServerAsync(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
ServerErrorCode: -2130575223
ServerErrorTypeName: Microsoft.SharePoint.SPException
ServerErrorTraceCorrelationId: 902d7ea0-30b4-1000-e802-e84cb01ade7d
ServerErrorValue:
ServerErrorDetails:
.       0ms
pwsh Information: 0 : 2022-12-02 13:30:58.3119  [List instances]        [10]    [Debug] Code execution scope ended      37928ms 4f001375-60b0-46f1-a95b-ce7beb954e8a
pwsh Information: 0 : 2022-12-02 13:30:58.3128  [ProvisioningTemplate WebHook Call]     [10]    [Debug] Code execution scope started    0ms     4f001375-60b0-46f1-a95b-ce7beb954e8a
pwsh Information: 0 : 2022-12-02 13:30:58.3134  [ProvisioningTemplate WebHook Call]     [10]    [Debug] Code execution scope ended      0ms     4f001375-60b0-46f1-a95b-ce7beb954e8a
pwsh Information: 0 : 2022-12-02 13:30:58.3141  [Provisioning]  [10]    [Debug] Code execution scope ended      106491ms        4f001375-60b0-46f1-a95b-ce7beb954e8a
```

**Comment by mpowney** [comment]
Version info:
PnP.PowerShell running on Windows 11, PowerShell 7.2.7

```
PS C:\Users\MarkPowney> Get-Module PnP.PowerShell

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Manifest   1.12.0                PnP.PowerShell                      {Add-PnPAlert, Add-PnPApp, Add-PnPApplicationCustomizer, Add-PnPAvailableSiteClassification…}
```

**Comment by mpowney** [comment]
Further info: the .pnp template included the default assets, including OOB libraries like Site Pages.  

As a work-around, we've recreated the .pnp template from the source site, using the ```-ListsToExtract``` parameter of the ```Get-PnPSiteTemplate``` PnP PowerShell cmdlet.  

The error "You are not allowed to rename this library." no longer occurs when the new .pnp template is invoked.

**Comment by mpowney** [comment]
When the original .pnp template with the OOB lists included was invoked against my own dev tenant, the debug messages suggest the following operations were the cause of it failing in the tenant:

```
pwsh Information: 0 : 2022-12-06 10:41:49.3081  [List instances]        [24]    [Debug] Added property bag entry IsAttachmentLibrary to list Committee Documents        43927ms a27d58b2-c828-4cc3-82ea-309607470183
pwsh Information: 0 : 2022-12-06 10:41:49.7204  [List instances]        [24]    [Debug] Added property bag entry SystemUsesListPolicy to list Preservation Hold Library 44339ms a27d58b2-c828-4cc3-82ea-309607470183
pwsh Information: 0 : 2022-12-06 10:41:50.0360  [List instances]        [24]    [Debug] Added property bag entry HasDirtyPolicy to list Preservation Hold Library       44655ms a27d58b2-c828-4cc3-82ea-309607470183
pwsh Information: 0 : 2022-12-06 10:41:50.3320  [List instances]        [24]    [Debug] Added property bag entry UseListPolicy to list Preservation Hold Library        44951ms a27d58b2-c828-4cc3-82ea-309607470183
pwsh Information: 0 : 2022-12-06 10:41:50.6181  [List instances]        [24]    [Debug] Added property bag entry dlc_listHasExpirationPolicy to list Preservation Hold Library  45237ms a27d58b2-c828-4cc3-82ea-309607470183
pwsh Information: 0 : 2022-12-06 10:41:50.7075  [List instances]        [24]    [Debug] Added property bag entry IsAttachmentLibrary to list Site Assets        45326ms a27d58b2-c828-4cc3-82ea-309607470183
```

This might be an indication that the "You are not allowed to rename this library." error is returned when the provisioning engine adds property bag values to the "Preservation Hold" library.

My own dev tenant has no data retention policies applied, whereas the original two tenants do have these policies applied.

**Comment by TomKronenburg** [comment]
we had the exact same issue. i think the actual issue is with sitepages library, but it could be preservation hold. We deleted everything from the site template xml file, starting at <pnp:Lists> and ending at </pnp:Lists>. All Lists content in the template was std stuff (documents, events, preservation hold etc) so deleting this from the template didn't cause us any problems. This solved the issue for us. 

It is weird though, that templates with this stuff in, have worked for years, and now no longer.

**Comment by TomKronenburg** [comment]
BTW: you cannot use -ListsToExtract without any variable. And as we don't have custom lists this options wasn't available to us.

**Comment by LutzD-pkb** [comment]
We have the exact same issue - working template now stopped working. We do have a data retention policy applied. Unfortunately, we add custom columns to the Site Pages library via the template so we can't just exclude it from the template.
