### ISSUE TITLE
Invoke-PnPSiteTemplate: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by aybouzaglou** [pnp/pnpframework#822]
I'm getting the following error when trying to import a PNP template. 
I'm using PowerShell 7.3.1

Get-PnPException is:
Message          : Object reference not set to an instance of an object.
Stacktrace       :    at PnP.PowerShell.Commands.Base.PnPConnectedCmdlet.ProcessRecord() in c:\build\src\Commands\Base\PnPConnectedCmdlet.cs:line 79
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in c:\build\src\Commands\Base\PnPSharePointCmdlet.cs:line 121
                      at System.Management.Automation.CommandProcessor.ProcessRecord()
ScriptLineNumber : 1

**Comment by whitehotaru** [comment]
I have a similar issue, @erwinvanhunen 
After creating a XML PnP-Sitetemplate with `Get-PnPSiteTemplate` and applying it with `Invoke-PnPSiteTemplate` I get an access denied error.

```Powershell
PS > Invoke-PnPSiteTemplate -Path ./CUSTOMER-Search-Center-Customization.xml                    
Invoke-PnPSiteTemplate: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
PS > Get-PnPException

Message          : Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
Stacktrace       :    at PnP.PowerShell.Commands.Base.PnPConnectedCmdlet.ProcessRecord() in c:\build\src\Commands\Base\PnPConnectedCmdlet.cs:line 93
                      at System.Management.Automation.Cmdlet.DoProcessRecord()
                      at System.Management.Automation.CommandProcessor.ProcessRecord()
ScriptLineNumber : 1
```
My PnP Template is quite simple:

```XML
<?xml version="1.0" encoding="utf-8"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2022/09/ProvisioningSchema">
  <pnp:Preferences Generator="PnP.Framework, Version=1.11.2.0, Culture=neutral, PublicKeyToken=0d501f89f11b748c" />
  <pnp:Templates ID="CONTAINER-TEMPLATE-EC63A3A6533D4AA19F07FCA4F1106C96">
    <pnp:ProvisioningTemplate ID="TEMPLATE-EC63A3A6533D4AA19F07FCA4F1106C96" Version="1" BaseSiteTemplate="SITEPAGEPUBLISHING#0" Scope="RootSite">
      <pnp:SiteSettings AllowDesigner="true" AllowCreateDeclarativeWorkflow="true" AllowSaveDeclarativeWorkflowAsTemplate="true" AllowSavePublishDeclarativeWorkflow="true" SearchBoxInNavBar="Inherit" SearchCenterUrl="https://customertenant.sharepoint.com/sites/somesitecollection/SitePages/search.aspx" />
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>
```
I did set the custom script status with `Set-PnPSite -NoScriptSite $false`, but get the error anyway. Scripts are allowed on tenant level.
<img width="1525" alt="image" src="https://user-images.githubusercontent.com/18051300/218124815-4b5ea458-7d81-4705-9328-2168023118a5.png">

´´´Powershell
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Darwin 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:53:49 PST 2023; root:xnu-8792.81.2~2/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by Rhapsidion** [comment]
Hi, I am experiencing this error all of a sudden as well now after running the same script a few days before - 
![image](https://github.com/pnp/pnpframework/assets/43815703/c51bd659-eedc-4cdf-981e-d102b46ab061)


I'm not sure why as I have correct permissions and am running PSVersion 7.3.11
