### ISSUE TITLE
SetListAutoRecordDeclaration is not working

### ISSUE THREAD

**Issue by frodale** [pnp/pnpframework#847]
Good evening,

When setting a list to declare records automatically: 

spList.SetListAutoRecordDeclaration(true);

I am getting an unauthorized access exception

_Microsoft.SharePoint.Client.ServerUnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServerAsync(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
   at Microsoft.SharePoint.Client.RecordsManagementExtensions.SetListAutoRecordDeclaration(List list, Boolean autoDeclareRecords)_

Just to add that this same code has been working fine for a while, so i am guessing this is some update being rolled out to some sharepoint tenants (as i discovered a couple of tenants without this issue)

**Comment by martinewald** [comment]
I'm having the same issue. Did you ever solve it?

**Comment by workleap-benoit-seguin** [comment]
I'm also having the same issue.
It seems that adding the Event Receivers [ref](https://github.com/pnp/pnpframework/blob/f5e85cfa8835bab41693bcca3883527b78c158a7/src/lib/PnP.Framework/Extensions/RecordsManagementExtensions.cs#L377) is no longer allowed.
When I debugged with a network tracer (Fiddler), all CSOM queries worked fine, except the one that added the event receivers.
The code works well on an on-premises version of SharePoint (tested on a 2016 instance).
