### ISSUE TITLE
AzureEnvironment parameter specified in the Connect-PnPOnline is not passed to the ClientContextSettings of the PnP context.

### ISSUE THREAD

**Issue by abhijeet-chatarjee** [pnp/pnpframework#867]
I am connecting to a non-tenant-admin site of a 'USGovernment' azure environment using the following command:

`Connect-PnPOnline -Url https://***.sharepoint.us/***/*** -ClientId *** -ClientSecret *** -AzureEnvironment USGovernment`

It is successful, but **Get-PnPTenantSite** after this fails with the following weird error:
`PS /home/support> Get-PnPTenantSite
Get-PnPTenantSite: '<' is an invalid start of a value. Path: $ | LineNumber: 2 | BytePositionInLine: 0.`

Following is the **stack trace** of the exception:

 `PS /home/support> Get-PnPException

Message          : '<' is an invalid start of a value. Path: $ | LineNumber: 2 | BytePositionInLine: 0.
Stacktrace       :    at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
                      at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
                      at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
                      at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
                      at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
                      at PnP.Framework.Utilities.TokenHelper.GetMetadataDocument(String realm)
                      at PnP.Framework.Utilities.TokenHelper.GetStsUrl(String realm)
                      at PnP.Framework.Utilities.TokenHelper.GetAppOnlyAccessToken(String targetPrincipalName, String targetHost, String targetRealm)
                      at PnP.Framework.Utilities.ACSTokenGenerator.GetToken(Uri siteUrl)
                      at PnP.Framework.AuthenticationManager.<GetContextAsync>b__56_0(String site)
                      at PnP.Framework.AuthenticationManager.<>c__DisplayClass68_0.<GetAccessTokenContext>b__0(Object sender, WebRequestEventArgs args)
                      at Microsoft.SharePoint.Client.ClientRuntimeContext.OnExecutingWebRequest(WebRequestEventArgs args)
                      at Microsoft.SharePoint.Client.ClientRuntimeContext.FireExecutingWebRequestEvent(WebRequestEventArgs args)
                      at Microsoft.SharePoint.Client.ClientRequest.SetupServerQuery(ChunkStringBuilder sb)
                      at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServerAsync(ChunkStringBuilder sb)
                      at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryAsync()
                      at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQueryAsync()
                      at Microsoft.SharePoint.Client.ClientContext.ExecuteQueryAsync()
                      at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount,
                    String userAgent)
                      at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, String u
                   serAgent)
                      at PnP.PowerShell.Commands.Base.PnPConnection.CloneContext(String url) in D:\a\powershell\powershell\src\Commands\Base\PnPConnection.cs
                   :line 612
                      at PnP.PowerShell.Commands.Base.PnPAdminCmdlet.BeginProcessing() in D:\a\powershell\powershell\src\Commands\Base\PnPAdminCmdlet.cs:line
                    79
                      at System.Management.Automation.Cmdlet.DoBeginProcessing()
                      at System.Management.Automation.CommandProcessorBase.DoBegin()
ScriptLineNumber : 1`

I debugged and found that the issue is while cloning the current clientContext for the tenant admin site as Get-PnPTenantSite requires access to the tenant admin site.
In **ClientContextExtensions.cs** file:
ClientContext **Clone**(this ClientRuntimeContext clientContext, ClientContext targetContext, Uri siteUrl, Dictionary<string, string>      accessTokens = null)
{
....
var contextSettings = clientContext.GetContextSettings();
....
newClientContext = authManager.GetACSAppOnlyContext(newSiteUrl, contextSettings.ClientId, contextSettings.ClientSecret, contextSettings.Environment);
}

Problem is that contextSettings.Environment is still pointing to AzureEnvironment.Production.
It means that the AzureEnvironment value is not passed to the contextSettings which is to be used for cloning the clientContext. And also means that the pnpframework is not currently being supported for other Azure environments.

THIS NEEDS TO BE FIXED.

**Comment by pkbullock** [comment]
Closing as Azure Environment selection now available.
