### ISSUE TITLE
Invoke-PnPSiteTemplate - Import Directory failed on MacOS

### ISSUE THREAD

**Issue by salascz** [pnp/pnpframework#991]
Hello,
there seems to be an issue with importing the whole directory on non Windows system.

I am using following declaration in my template.xml file:
```
<pnp:Files>
  <pnp:Directory Src="files/" Folder="SiteAssets/Data" Overwrite="true" Level="Published" />
</pnp:Files>
```

The operation failed with error:
`An error occurred:  Value cannot be null. (Parameter 'clientObject') `

Trace Log:
```
[PnP.Framework]	[0]	[Error]	ExecuteQuery threw following exception: Microsoft.SharePoint.Client.ServerException: The file or folder name "SiteAssets/Data/files\test-file.html" contains invalid characters. Please use a different name. Common invalid characters include the following: # % * : < > ? /  |
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServerAsync(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
```

Please note, there seems to be backslash symbol (**\**) used in file path...

### Expected behavior
I should be able to import the directory from MacOS similar to Windows

### What is the version of the Cmdlet module you are running?
PnP.PowerShell version 2.3.0

**Comment by maxali** [comment]
Facing the same issue.
PnP.PowerShell version 2.4.0

**Comment by robpearmain** [comment]
I am having the same issue using 1.11.0 on MacOS, has this been fixed in more recent release ?

As a workaround I used File as I only had one file to transfer from SiteAssets, but this error occurs on a Mac when using Directory.

The operation failed with error:

`An error occurred:  Value cannot be null. (Parameter 'clientObject') `

With the following:

`<pnp:Files>
       <pnp:Directory 
Src="files" Folder="SiteAssets" Overwrite="true" Level="Published" /> 
 </pnp:Files>`

This works

`<pnp:Files>
        <pnp:File
          Src="files/myfile.docx"
          Folder="SiteAssets"
          Overwrite="true"
          Level="Published" />
      </pnp:Files>`
